
export const MSG_ACCESO = {
    ACCESO_OK: 'ACCESO CORRECTO',
    ACCESO_DENEGADO: 'ACCESO DENEGADO',
    DATOS_INCORRECTOS: 'EL USUARIO O LA CLAVE SON INCORRECTOS'
}

export const CONS_URL = {
    PAGE_HOME: '/',
    PAGE_MOSTRARDATOS: '/MostrarDatos',
    PAGE_NOSOTROS : '/Nosotros',
    PAGE_CONTACTO : '/Contacto'
}
